### ISSUE TITLE
PDFBox 2.x-version

### ISSUE THREAD

**Issue by madsop-nav** [openhtmltopdf/openhtmltopdf#5]
On my team, the upgrade from PDFBox 2.x to 3.x turned out to be non-trivial.

Hence, I'm considering making a branch in this repo without the PDFBox upgrade, for those wanting to switch over from the original repo to this one without having to do the PDFBox upgrade at the same time.

Of course, this is a trade-off, as there are maintenance costs to it, but for teams like mine, it'd be very useful.

**Comment by siegelzc** [comment]
I'm not keen on maintaining the second branch myself, but if your team needs it, it's a choice of maintaining a branch here or in a fork. I don't mind it being here. The upgrade here to PDFBox 3 was actually fairly small in terms of LOC diff (see revision: `16b6dd543c49f22fa421f32e77b6316cd0274e9e`), so it may not actually be much work to maintain the other branch. 

Alternatively there is the option of maintaining a parallel `openhtmltopdf-pdfbox2` module on the main branch. This might make releases easier, but I'm leaning against it. This option may be annoying since the examples/testing modules depend on the main `openhtmltopdf-pdfbox` module already, and it may be harder to leverage git rebase/cherry-pick to roll in the newer changes. Just throwing out the idea in case someone likes it.

**Comment by madsop-nav** [comment]
To be clear about my idea here: To release a version with PDFBox 2, under the new organization, and with the CVEs from batik 1.14 fixed. To lower the bar for those that run into issues of any kind upgrading to PDFBox 3. So I'm not suggesting much maintenance or work on this branch, just as a starting point.

Shouldn't take long to do, once we've established the release pipeline properly.

**Comment by siegelzc** [comment]
Oh I see what you're saying. So we'll maintain security patches on the old version, but all new development will be exclusive to the current branch.

**Comment by madsop-nav** [comment]
Spot on!

**Comment by madsop-nav** [comment]
I've created a pdfbox 2 branch, and done git revert on the commits with code changes done since the pdfbox 3 upgrade (but kept the workflow changes etc), and each push to this branch creates a release prefixed with `pdfbox2`. Good enough for now, I think.

**Comment by siegelzc** [comment]
@madsop-nav 

Is [this release](https://github.com/openhtmltopdf/openhtmltopdf/releases/tag/20240305100350) sufficient for what you needed? Can this issue be closed?

**Comment by madsop-nav** [comment]
Yep, I'm happy with what we've got on this now.

We might consider adding a section to the readme about it, but the flip side of that is that we make it kind of officially supported, which I'm not sure that we want to. Leaving it as is for now, but might reconsider later.
